logfile=logs/sc_serv.log
w3clog=logs/sc_w3c.log
banfile=control/sc_serv.ban
ripfile=control/sc_serv.rip

portbase=8000

password=thealphadio32
adminpassword=thealphacraft41

requirestreamconfigs=0

maxuser=100
publicserver=never